version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: bprjatim
        container_name: bprjatim-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        network_mode: host
